// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimationCode: typeof import('./src/components/animation/AnimationCode.vue')['default']
    AnimationOptions: typeof import('./src/components/animation/AnimationOptions.vue')['default']
    AnimationPreview: typeof import('./src/components/animation/AnimationPreview.vue')['default']
    CelebrationCheckbox: typeof import('./src/components/generic/CelebrationCheckbox.vue')['default']
    CustomIcon: typeof import('./src/components/CustomIcon.vue')['default']
    FooterButtons: typeof import('./src/components/FooterButtons.vue')['default']
    KeyframesCanvas: typeof import('./src/components/keyframesCanvas/KeyframesCanvas.vue')['default']
    KeyframesCanvasGuideHorizontal: typeof import('./src/components/keyframesCanvas/KeyframesCanvasGuideHorizontal.vue')['default']
    KeyframesCanvasGuides: typeof import('./src/components/keyframesCanvas/KeyframesCanvasGuides.vue')['default']
    KeyframesCanvasGuideVertical: typeof import('./src/components/keyframesCanvas/KeyframesCanvasGuideVertical.vue')['default']
    KeyframesCanvasInstructions: typeof import('./src/components/keyframesCanvas/KeyframesCanvasInstructions.vue')['default']
    KeyframesCanvasLine: typeof import('./src/components/keyframesCanvas/KeyframesCanvasLine.vue')['default']
    KeyframesCanvasNewPoint: typeof import('./src/components/keyframesCanvas/KeyframesCanvasNewPoint.vue')['default']
    KeyframesCanvasPoint: typeof import('./src/components/keyframesCanvas/KeyframesCanvasPoint.vue')['default']
    KeyframesCanvasPointsMask: typeof import('./src/components/keyframesCanvas/KeyframesCanvasPointsMask.vue')['default']
    KeyframesCanvasPreview: typeof import('./src/components/keyframesCanvas/KeyframesCanvasPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallScreenPopup: typeof import('./src/components/SmallScreenPopup.vue')['default']
    UpdateBanner: typeof import('./src/components/UpdateBanner.vue')['default']
    WelcomePopup: typeof import('./src/components/WelcomePopup.vue')['default']
  }
}
