[build]
publish = "dist"
command = "yarn build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true

[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"
