[build]
  publish = "dist"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    skip = true
  [plugins.inputs.onSuccess]
    enable = true
    record = true
