name: CI

on: push

jobs:
  e2e_tests:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: ⚙️ Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: ⚙️ Install serve
        run: npm install -g serve

      - name: 🤖 Run the tests
        uses: cypress-io/github-action@v2
        with:
          # record: true
          browser: chrome
          build: npm run build
          start: 'serve dist -l 4173'
          wait-on: 'http://localhost:4173'
          wait-on-timeout: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
